services:
  db:
    image: mysql:8.4.5
    container_name: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    command: --general-log=1 --general-log-file=/etc/mysql/conf.d/general.log
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql_logs:/etc/mysql/conf.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    env_file:
      - .env
    image: redis:7
    container_name: redis
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data


volumes:
  db_data:
  redis_data: